INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (4, 'Eagan', 2);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (5, 'Los Angeles', 2);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (6, 'Astana', 3);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (7, 'Baykonur', 3);